# type: 0 equity, 1 futures, 2 options
# expiry_type: .na.interger: no expiry date,
ETF:
  product_id: ETF
  type: 0
  price_tick: 0.001
  volume_multiple: 1.0
  cost_ratio: 0.001
  cost_const: 0.0e+00
  initial_margin_ratio: 1.0
  allow_open_sell: no
  allow_close_today: no
  expiry_type: .na.integer
  exchange:
    - SH
    - SZ
index:
  product_id: index
  type: 0
  price_tick: 0.0001
  volume_multiple: 1.0
  cost_ratio: 0.001
  cost_const: 0.0e+00
  initial_margin_ratio: 1.0
  allow_open_sell: no
  allow_close_today: no
  expiry_type: .na.integer
  exchange:
    - SH
    - SZ
stock:
  product_id: stock
  type: 0
  price_tick: 0.01
  volume_multiple: 1.0
  cost_ratio: 0.001
  cost_const: 0.0e+00
  initial_margin_ratio: 1.0
  allow_open_sell: no
  allow_close_today: no
  expiry_type: .na.integer
  exchange:
    - SH
    - SZ
a:
  product_id: a
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 2.4
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
ag:
  product_id: ag
  type: 1
  price_tick: 1.0
  volume_multiple: 15.0
  cost_ratio: 9.0e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.12
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
al:
  product_id: al
  type: 1
  price_tick: 5.0
  volume_multiple: 5.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
AP:
  product_id: AP
  type: 1
  price_tick: 1.0
  volume_multiple: 5.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: CZC
au:
  product_id: au
  type: 1
  price_tick: 0.05
  volume_multiple: 1000.0
  cost_ratio: 0.0e+00
  cost_const: 18.0
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
b:
  product_id: b
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 3.6
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
bb:
  product_id: bb
  type: 1
  price_tick: 0.05
  volume_multiple: 500.0
  cost_ratio: 0.0018
  cost_const: 0.0e+00
  initial_margin_ratio: 0.2
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
bu:
  product_id: bu
  type: 1
  price_tick: 2.0
  volume_multiple: 10.0
  cost_ratio: 5.4e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.14
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
c:
  product_id: c
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 2.16
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
CF:
  product_id: CF
  type: 1
  price_tick: 5.0
  volume_multiple: 5.0
  cost_ratio: 0.0e+00
  cost_const: 7.74
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: CZC
cs:
  product_id: cs
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 2.7
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
cu:
  product_id: cu
  type: 1
  price_tick: 10.0
  volume_multiple: 5.0
  cost_ratio: 8.25e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.13
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
CY:
  product_id: CY
  type: 1
  price_tick: 5
  volume_multiple: 5.0
  cost_ratio: 8.25e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: CZC
fb:
  product_id: fb
  type: 1
  price_tick: 0.05
  volume_multiple: 500.0
  cost_ratio: 0.00018
  cost_const: 0.0e+00
  initial_margin_ratio: 0.2
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
FG:
  product_id: FG
  type: 1
  price_tick: 1.0
  volume_multiple: 20.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: CZC
fu:
  product_id: fu
  type: 1
  price_tick: 1.0
  volume_multiple: 50.0
  cost_ratio: 3.6e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.24
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 2
  exchange: SHF
hc:
  product_id: hc
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 7.2e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.11
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
i:
  product_id: i
  type: 1
  price_tick: 0.5
  volume_multiple: 100.0
  cost_ratio: 0.000108
  cost_const: 0.0e+00
  initial_margin_ratio: 0.11
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
IC:
  product_id: IC
  type: 1
  price_tick: 0.2
  volume_multiple: 200.0
  cost_ratio: 0.0001
  cost_const: 0.0e+00
  initial_margin_ratio: 0.4
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 6
  exchange: CFE
IF:
  product_id: IF
  type: 1
  price_tick: 0.2
  volume_multiple: 300.0
  cost_ratio: 0.0001
  cost_const: 0.0e+00
  initial_margin_ratio: 0.4
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 6
  exchange: CFE
IH:
  product_id: IH
  type: 1
  price_tick: 0.2
  volume_multiple: 300.0
  cost_ratio: 0.0001
  cost_const: 0.0e+00
  initial_margin_ratio: 0.4
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 6
  exchange: CFE
j:
  product_id: j
  type: 1
  price_tick: 0.5
  volume_multiple: 100.0
  cost_ratio: 0.000108
  cost_const: 0.0e+00
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
jd:
  product_id: jd
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 0.00027
  cost_const: 0.0e+00
  initial_margin_ratio: 0.11
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
jm:
  product_id: jm
  type: 1
  price_tick: 0.5
  volume_multiple: 60.0
  cost_ratio: 0.000108
  cost_const: 0.0e+00
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
JR:
  product_id: JR
  type: 1
  price_tick: 1
  volume_multiple: 20
  cost_ratio: 0.000108
  cost_const: 0.0e+00
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: CZC
l:
  product_id: l
  type: 1
  price_tick: 5.0
  volume_multiple: 5.0
  cost_ratio: 0.0e+00
  cost_const: 3.6
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
LR:
  product_id: LR
  type: 1
  price_tick: 1.0
  volume_multiple: 20.0
  cost_ratio: 0.0e+00
  cost_const: 3.6
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: CZC
m:
  product_id: m
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 2.7
  initial_margin_ratio: 0.08
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
MA:
  product_id: MA
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 2.52
  initial_margin_ratio: 0.11
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: CZC
ni:
  product_id: ni
  type: 1
  price_tick: 10.0
  volume_multiple: 1.0
  cost_ratio: 0.0e+00
  cost_const: 10.8
  initial_margin_ratio: 0.14
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
OI:
  product_id: OI
  type: 1
  price_tick: 2.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 4.5
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: CZC
p:
  product_id: p
  type: 1
  price_tick: 2.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 4.5
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
pb:
  product_id: pb
  type: 1
  price_tick: 5.0
  volume_multiple: 5.0
  cost_ratio: 7.2e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.08
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
PM:
  product_id: PM
  type: 1
  price_tick: 1
  volume_multiple: 50
  cost_ratio: 7.2e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.08
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: CZC
pp:
  product_id: pp
  type: 1
  price_tick: 1.0
  volume_multiple: 5.0
  cost_ratio: 9.0e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
rb:
  product_id: rb
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 8.1e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.11
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
RI:
  product_id: RI
  type: 1
  price_tick: 1
  volume_multiple: 20
  cost_ratio: 7.2e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.08
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: CZC
RM:
  product_id: RM
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 2.7
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: CZC
RS:
  product_id: RS
  type: 1
  price_tick: 1
  volume_multiple: 10
  cost_ratio: 7.2e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.08
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: CZC
ru:
  product_id: ru
  type: 1
  price_tick: 5.0
  volume_multiple: 10.0
  cost_ratio: 8.1e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.11
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
sc:
  product_id: sc
  type: 1
  price_tick: 0.1
  volume_multiple: 1000.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: INE
SF:
  product_id: SF
  type: 1
  price_tick: 2.0
  volume_multiple: 5.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: CZC
SM:
  product_id: SM
  type: 1
  price_tick: 2.0
  volume_multiple: 5.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: CZC
sn:
  product_id: sn
  type: 1
  price_tick: 10.0
  volume_multiple: 1.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: SHF
SR:
  product_id: SR
  type: 1
  price_tick: 1.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: CZC
T:
  product_id: T
  type: 1
  price_tick: 0.005
  volume_multiple: 10000.0
  cost_ratio: 0.0e+00
  cost_const: 7.5
  initial_margin_ratio: 0.03
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 7
  exchange: CFE
TA:
  product_id: TA
  type: 1
  price_tick: 2.0
  volume_multiple: 5.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 4
  exchange: CZC
TC:
  product_id: TC
  type: 1
  price_tick: 0.2
  volume_multiple: 200.0
  cost_ratio: 0.0e+00
  cost_const: 14.4
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 5
  exchange: CZC
TF:
  product_id: TF
  type: 1
  price_tick: 0.005
  volume_multiple: 10000.0
  cost_ratio: 0.0e+00
  cost_const: 7.5
  initial_margin_ratio: 0.022
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 7
  exchange: CFE
TS:
  product_id: TS
  type: 1
  price_tick: 0.005
  volume_multiple: 10000.0
  cost_ratio: 0.0e+00
  cost_const: 7.5
  initial_margin_ratio: 0.022
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 7
  exchange: CFE
v:
  product_id: v
  type: 1
  price_tick: 5.0
  volume_multiple: 5.0
  cost_ratio: 0.0e+00
  cost_const: 4.5
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
WH:
  product_id: WH
  type: 1
  price_tick: 1
  volume_multiple: 20
  cost_ratio: 7.2e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.08
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: CZC
wr:
  product_id: wr
  type: 1
  price_tick: 1
  volume_multiple: 10
  cost_ratio: 7.2e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.08
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
'y':
  product_id: 'y'
  type: 1
  price_tick: 2.0
  volume_multiple: 10.0
  cost_ratio: 0.0e+00
  cost_const: 4.5
  initial_margin_ratio: 0.09
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 3
  exchange: DCE
zn:
  product_id: zn
  type: 1
  price_tick: 5.0
  volume_multiple: 5.0
  cost_ratio: 0.0e+00
  cost_const: 5.4
  initial_margin_ratio: 0.11
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: SHF
OP_m:
  product_id: OP_m
  type: 2
  price_tick: 0.0001
  volume_multiple: 300000.0
  cost_ratio: 0.0e+00
  cost_const: 3.5
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: .na.integer
  exchange: DCE
ZC:
  product_id: ZC
  type: 1
  price_tick: 0.2
  volume_multiple: 100
  cost_ratio: 7.2e-05
  cost_const: 0.0e+00
  initial_margin_ratio: 0.08
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: 1
  exchange: CZC
OP_SR:
  product_id: OP_SR
  type: 2
  price_tick: 0.0001
  volume_multiple: 300000.0
  cost_ratio: 0.0e+00
  cost_const: 3.5
  initial_margin_ratio: 0.1
  allow_open_sell: yes
  allow_close_today: yes
  expiry_type: .na.integer
  exchange: CZC
